// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentSearch(arg1) {
  return window['go']['app']['App']['AddRecentSearch'](arg1);
}

export function CheckpointDatabase() {
  return window['go']['app']['App']['CheckpointDatabase']();
}

export function CleanOrphanedLinks() {
  return window['go']['app']['App']['CleanOrphanedLinks']();
}

export function CreateEntity(arg1) {
  return window['go']['app']['App']['CreateEntity'](arg1);
}

export function CreateRelationship(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateRelationship'](arg1, arg2, arg3);
}

export function DeleteEntity(arg1) {
  return window['go']['app']['App']['DeleteEntity'](arg1);
}

export function DeleteEntityImage(arg1) {
  return window['go']['app']['App']['DeleteEntityImage'](arg1);
}

export function DeleteRelationship(arg1) {
  return window['go']['app']['App']['DeleteRelationship'](arg1);
}

export function DeleteSavedSearch(arg1) {
  return window['go']['app']['App']['DeleteSavedSearch'](arg1);
}

export function EntityService() {
  return window['go']['app']['App']['EntityService']();
}

export function ExportToJSON() {
  return window['go']['app']['App']['ExportToJSON']();
}

export function ExportToMarkdown() {
  return window['go']['app']['App']['ExportToMarkdown']();
}

export function GetAllGraphData() {
  return window['go']['app']['App']['GetAllGraphData']();
}

export function GetAllRelationships() {
  return window['go']['app']['App']['GetAllRelationships']();
}

export function GetAllSettings() {
  return window['go']['app']['App']['GetAllSettings']();
}

export function GetAllSources() {
  return window['go']['app']['App']['GetAllSources']();
}

export function GetAppConfig() {
  return window['go']['app']['App']['GetAppConfig']();
}

export function GetAppConfigContent() {
  return window['go']['app']['App']['GetAppConfigContent']();
}

export function GetCapabilities() {
  return window['go']['app']['App']['GetCapabilities']();
}

export function GetConstants() {
  return window['go']['app']['App']['GetConstants']();
}

export function GetDanglingRelationships() {
  return window['go']['app']['App']['GetDanglingRelationships']();
}

export function GetDatabaseFileSize() {
  return window['go']['app']['App']['GetDatabaseFileSize']();
}

export function GetDatabasePath() {
  return window['go']['app']['App']['GetDatabasePath']();
}

export function GetDuplicateEntities() {
  return window['go']['app']['App']['GetDuplicateEntities']();
}

export function GetEgoGraph(arg1, arg2) {
  return window['go']['app']['App']['GetEgoGraph'](arg1, arg2);
}

export function GetEntitiesWithUnknownTypes() {
  return window['go']['app']['App']['GetEntitiesWithUnknownTypes']();
}

export function GetEntitiesWithoutDescriptions() {
  return window['go']['app']['App']['GetEntitiesWithoutDescriptions']();
}

export function GetEntity(arg1) {
  return window['go']['app']['App']['GetEntity'](arg1);
}

export function GetEntityImage(arg1) {
  return window['go']['app']['App']['GetEntityImage'](arg1);
}

export function GetEnvLocation() {
  return window['go']['app']['App']['GetEnvLocation']();
}

export function GetEnvVars() {
  return window['go']['app']['App']['GetEnvVars']();
}

export function GetExtendedStats() {
  return window['go']['app']['App']['GetExtendedStats']();
}

export function GetImageCacheInfo() {
  return window['go']['app']['App']['GetImageCacheInfo']();
}

export function GetLinkedEntitiesNotInDescription() {
  return window['go']['app']['App']['GetLinkedEntitiesNotInDescription']();
}

export function GetMarkedEntities() {
  return window['go']['app']['App']['GetMarkedEntities']();
}

export function GetNavigationHistory() {
  return window['go']['app']['App']['GetNavigationHistory']();
}

export function GetOrphanedEntities() {
  return window['go']['app']['App']['GetOrphanedEntities']();
}

export function GetRandomEntity() {
  return window['go']['app']['App']['GetRandomEntity']();
}

export function GetRecentSearches() {
  return window['go']['app']['App']['GetRecentSearches']();
}

export function GetReferencePattern() {
  return window['go']['app']['App']['GetReferencePattern']();
}

export function GetRelationships(arg1) {
  return window['go']['app']['App']['GetRelationships'](arg1);
}

export function GetRelationshipsWithDetails(arg1) {
  return window['go']['app']['App']['GetRelationshipsWithDetails'](arg1);
}

export function GetSavedSearches() {
  return window['go']['app']['App']['GetSavedSearches']();
}

export function GetSelfReferentialEntities() {
  return window['go']['app']['App']['GetSelfReferentialEntities']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetStats() {
  return window['go']['app']['App']['GetStats']();
}

export function GetTTSCacheInfo() {
  return window['go']['app']['App']['GetTTSCacheInfo']();
}

export function GetTopHubs(arg1) {
  return window['go']['app']['App']['GetTopHubs'](arg1);
}

export function GetUnknownTags() {
  return window['go']['app']['App']['GetUnknownTags']();
}

export function GetUnlinkedReferences() {
  return window['go']['app']['App']['GetUnlinkedReferences']();
}

export function GetWindowGeometry() {
  return window['go']['app']['App']['GetWindowGeometry']();
}

export function Greet(arg1) {
  return window['go']['app']['App']['Greet'](arg1);
}

export function HasEnvFile() {
  return window['go']['app']['App']['HasEnvFile']();
}

export function ImageService() {
  return window['go']['app']['App']['ImageService']();
}

export function MergeDuplicateEntities(arg1, arg2) {
  return window['go']['app']['App']['MergeDuplicateEntities'](arg1, arg2);
}

export function RemoveRecentSearch(arg1) {
  return window['go']['app']['App']['RemoveRecentSearch'](arg1);
}

export function RunAdHocQuery(arg1) {
  return window['go']['app']['App']['RunAdHocQuery'](arg1);
}

export function SaveAppConfigContent(arg1) {
  return window['go']['app']['App']['SaveAppConfigContent'](arg1);
}

export function SaveCurrentSearch(arg1) {
  return window['go']['app']['App']['SaveCurrentSearch'](arg1);
}

export function SaveEntityImage(arg1, arg2) {
  return window['go']['app']['App']['SaveEntityImage'](arg1, arg2);
}

export function SaveEnvVar(arg1, arg2) {
  return window['go']['app']['App']['SaveEnvVar'](arg1, arg2);
}

export function SaveIncomingCollapsed(arg1) {
  return window['go']['app']['App']['SaveIncomingCollapsed'](arg1);
}

export function SaveLastView(arg1) {
  return window['go']['app']['App']['SaveLastView'](arg1);
}

export function SaveLastWord(arg1) {
  return window['go']['app']['App']['SaveLastWord'](arg1);
}

export function SaveLeftbarWidth(arg1) {
  return window['go']['app']['App']['SaveLeftbarWidth'](arg1);
}

export function SaveOutgoingCollapsed(arg1) {
  return window['go']['app']['App']['SaveOutgoingCollapsed'](arg1);
}

export function SaveReportItemHealthCollapsed(arg1) {
  return window['go']['app']['App']['SaveReportItemHealthCollapsed'](arg1);
}

export function SaveReportLinkIntegrityCollapsed(arg1) {
  return window['go']['app']['App']['SaveReportLinkIntegrityCollapsed'](arg1);
}

export function SaveRevealMarkdown(arg1) {
  return window['go']['app']['App']['SaveRevealMarkdown'](arg1);
}

export function SaveSearch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveSearch'](arg1, arg2, arg3, arg4);
}

export function SaveTabSelection(arg1, arg2) {
  return window['go']['app']['App']['SaveTabSelection'](arg1, arg2);
}

export function SaveTableSort(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveTableSort'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveWindowPosition(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SaveWindowPosition'](arg1, arg2, arg3, arg4);
}

export function SearchEntities(arg1, arg2) {
  return window['go']['app']['App']['SearchEntities'](arg1, arg2);
}

export function SelectExportFolder() {
  return window['go']['app']['App']['SelectExportFolder']();
}

export function SkipAiSetup() {
  return window['go']['app']['App']['SkipAiSetup']();
}

export function SpeakWord(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SpeakWord'](arg1, arg2, arg3, arg4);
}

export function TTSService() {
  return window['go']['app']['App']['TTSService']();
}

export function ToggleEntityMark(arg1, arg2) {
  return window['go']['app']['App']['ToggleEntityMark'](arg1, arg2);
}

export function UpdateEntity(arg1) {
  return window['go']['app']['App']['UpdateEntity'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}
