// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {services} from '../models';
import {config} from '../models';
import {app} from '../models';
import {settings} from '../models';

export function AddRecentSearch(arg1:string):Promise<void>;

export function CheckpointDatabase():Promise<void>;

export function CleanOrphanedLinks():Promise<number>;

export function CreateEntity(arg1:db.Entity):Promise<number>;

export function CreateRelationship(arg1:number,arg2:number,arg3:string):Promise<void>;

export function DeleteEntity(arg1:number):Promise<void>;

export function DeleteEntityImage(arg1:number):Promise<void>;

export function DeleteRelationship(arg1:number):Promise<void>;

export function DeleteSavedSearch(arg1:string):Promise<void>;

export function EntityService():Promise<services.EntityService>;

export function ExportToJSON():Promise<string>;

export function ExportToMarkdown():Promise<string>;

export function GetAllGraphData():Promise<services.GraphData>;

export function GetAllRelationships():Promise<Array<db.Relationship>>;

export function GetAllSettings():Promise<Record<string, any>>;

export function GetAllSources():Promise<Array<db.Source>>;

export function GetAppConfig():Promise<config.AppConfig>;

export function GetAppConfigContent():Promise<string>;

export function GetCapabilities():Promise<app.Capabilities>;

export function GetConstants():Promise<Record<string, string>>;

export function GetDanglingRelationships():Promise<Array<services.DanglingRelationshipResult>>;

export function GetDatabaseFileSize():Promise<number>;

export function GetDatabasePath():Promise<string>;

export function GetDuplicateEntities():Promise<Array<services.DuplicateEntityResult>>;

export function GetEgoGraph(arg1:number,arg2:number):Promise<services.GraphData>;

export function GetEntitiesWithUnknownTypes():Promise<Array<services.EntityWithUnknownTypeResult>>;

export function GetEntitiesWithoutDescriptions():Promise<Array<services.EntityWithoutDescriptionResult>>;

export function GetEntity(arg1:number):Promise<db.Entity>;

export function GetEntityImage(arg1:number):Promise<string>;

export function GetEnvLocation():Promise<string>;

export function GetEnvVars():Promise<Record<string, string>>;

export function GetExtendedStats():Promise<db.DashboardStats>;

export function GetImageCacheInfo():Promise<app.ImageCacheInfo>;

export function GetLinkedEntitiesNotInDescription():Promise<Array<services.LinkedEntityNotInDescriptionResult>>;

export function GetMarkedEntities():Promise<Array<db.Entity>>;

export function GetNavigationHistory():Promise<Array<db.Entity>>;

export function GetOrphanedEntities():Promise<Array<services.OrphanedEntityResult>>;

export function GetRandomEntity():Promise<db.Entity>;

export function GetRecentSearches():Promise<Array<string>>;

export function GetReferencePattern():Promise<string>;

export function GetRelationships(arg1:number):Promise<Array<db.Relationship>>;

export function GetRelationshipsWithDetails(arg1:number):Promise<Array<services.RelationshipDetail>>;

export function GetSavedSearches():Promise<Array<settings.SavedSearch>>;

export function GetSelfReferentialEntities():Promise<Array<services.SelfReferenceResult>>;

export function GetSettings():Promise<settings.Settings>;

export function GetStats():Promise<Record<string, number>>;

export function GetTTSCacheInfo():Promise<app.TTSCacheInfo>;

export function GetTopHubs(arg1:number):Promise<Array<db.Entity>>;

export function GetUnknownTags():Promise<Array<services.UnknownTagResult>>;

export function GetUnlinkedReferences():Promise<Array<services.UnlinkedReferenceResult>>;

export function GetWindowGeometry():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function HasEnvFile():Promise<boolean>;

export function ImageService():Promise<services.ImageService>;

export function MergeDuplicateEntities(arg1:number,arg2:Array<number>):Promise<void>;

export function RemoveRecentSearch(arg1:string):Promise<void>;

export function RunAdHocQuery(arg1:string):Promise<Array<Record<string, any>>>;

export function SaveAppConfigContent(arg1:string):Promise<void>;

export function SaveCurrentSearch(arg1:string):Promise<void>;

export function SaveEntityImage(arg1:number,arg2:string):Promise<void>;

export function SaveEnvVar(arg1:string,arg2:string):Promise<void>;

export function SaveIncomingCollapsed(arg1:boolean):Promise<void>;

export function SaveLastView(arg1:string):Promise<void>;

export function SaveLastWord(arg1:number):Promise<void>;

export function SaveLeftbarWidth(arg1:number):Promise<void>;

export function SaveOutgoingCollapsed(arg1:boolean):Promise<void>;

export function SaveReportItemHealthCollapsed(arg1:boolean):Promise<void>;

export function SaveReportLinkIntegrityCollapsed(arg1:boolean):Promise<void>;

export function SaveRevealMarkdown(arg1:boolean):Promise<void>;

export function SaveSearch(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<void>;

export function SaveTabSelection(arg1:string,arg2:string):Promise<void>;

export function SaveTableSort(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveWindowPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SearchEntities(arg1:string,arg2:string):Promise<Array<db.Entity>>;

export function SelectExportFolder():Promise<string>;

export function SkipAiSetup():Promise<void>;

export function SpeakWord(arg1:string,arg2:string,arg3:string,arg4:number):Promise<services.TTSResult>;

export function TTSService():Promise<services.TTSService>;

export function ToggleEntityMark(arg1:number,arg2:boolean):Promise<void>;

export function UpdateEntity(arg1:db.Entity):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;
