// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {services} from '../models';

export function CreateEntity(arg1:database.Entity):Promise<number>;

export function CreateRelationship(arg1:number,arg2:number,arg3:string):Promise<void>;

export function DeleteEntity(arg1:number):Promise<void>;

export function DeleteRelationship(arg1:number):Promise<void>;

export function GetAllEntities():Promise<Array<database.Entity>>;

export function GetAllGraphData():Promise<services.GraphData>;

export function GetAllRelationships():Promise<Array<database.Relationship>>;

export function GetEgoGraph(arg1:number):Promise<services.GraphData>;

export function GetEntity(arg1:number):Promise<database.Entity>;

export function GetExtendedStats():Promise<database.DashboardStats>;

export function GetMarkedEntities():Promise<Array<database.Entity>>;

export function GetRandomEntity():Promise<database.Entity>;

export function GetRelationships(arg1:number):Promise<Array<database.Relationship>>;

export function GetRelationshipsWithDetails(arg1:number):Promise<Array<services.RelationshipDetail>>;

export function GetTopHubs(arg1:number):Promise<Array<database.Entity>>;

export function SearchEntities(arg1:string,arg2:string):Promise<Array<database.Entity>>;

export function SearchEntitiesWithOptions(arg1:string,arg2:Array<string>,arg3:string):Promise<Array<database.Entity>>;

export function UpdateEntity(arg1:database.Entity):Promise<void>;
