// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateEntity(arg1) {
  return window['go']['services']['EntityService']['CreateEntity'](arg1);
}

export function CreateRelationship(arg1, arg2, arg3) {
  return window['go']['services']['EntityService']['CreateRelationship'](arg1, arg2, arg3);
}

export function DeleteEntity(arg1) {
  return window['go']['services']['EntityService']['DeleteEntity'](arg1);
}

export function DeleteRelationship(arg1) {
  return window['go']['services']['EntityService']['DeleteRelationship'](arg1);
}

export function GetAllEntities() {
  return window['go']['services']['EntityService']['GetAllEntities']();
}

export function GetAllGraphData() {
  return window['go']['services']['EntityService']['GetAllGraphData']();
}

export function GetAllRelationships() {
  return window['go']['services']['EntityService']['GetAllRelationships']();
}

export function GetEgoGraph(arg1) {
  return window['go']['services']['EntityService']['GetEgoGraph'](arg1);
}

export function GetEntity(arg1) {
  return window['go']['services']['EntityService']['GetEntity'](arg1);
}

export function GetExtendedStats() {
  return window['go']['services']['EntityService']['GetExtendedStats']();
}

export function GetMarkedEntities() {
  return window['go']['services']['EntityService']['GetMarkedEntities']();
}

export function GetRandomEntity() {
  return window['go']['services']['EntityService']['GetRandomEntity']();
}

export function GetRelationships(arg1) {
  return window['go']['services']['EntityService']['GetRelationships'](arg1);
}

export function GetRelationshipsWithDetails(arg1) {
  return window['go']['services']['EntityService']['GetRelationshipsWithDetails'](arg1);
}

export function GetTopHubs(arg1) {
  return window['go']['services']['EntityService']['GetTopHubs'](arg1);
}

export function SearchEntities(arg1, arg2) {
  return window['go']['services']['EntityService']['SearchEntities'](arg1, arg2);
}

export function SearchEntitiesWithOptions(arg1, arg2, arg3) {
  return window['go']['services']['EntityService']['SearchEntitiesWithOptions'](arg1, arg2, arg3);
}

export function SetDB(arg1) {
  return window['go']['services']['EntityService']['SetDB'](arg1);
}

export function UpdateEntity(arg1) {
  return window['go']['services']['EntityService']['UpdateEntity'](arg1);
}
