// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEntityImage(arg1:number):Promise<void>;

export function GetEntityImage(arg1:number):Promise<string>;

export function SaveEntityImage(arg1:number,arg2:string):Promise<void>;
