// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteEntityImage(arg1) {
  return window['go']['services']['ImageService']['DeleteEntityImage'](arg1);
}

export function GetEntityImage(arg1) {
  return window['go']['services']['ImageService']['GetEntityImage'](arg1);
}

export function SaveEntityImage(arg1, arg2) {
  return window['go']['services']['ImageService']['SaveEntityImage'](arg1, arg2);
}

export function SetDB(arg1) {
  return window['go']['services']['ImageService']['SetDB'](arg1);
}
