// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SetDB(arg1) {
  return window['go']['services']['TTSService']['SetDB'](arg1);
}

export function SpeakWord(arg1, arg2, arg3, arg4) {
  return window['go']['services']['TTSService']['SpeakWord'](arg1, arg2, arg3, arg4);
}
