// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function SpeakWord(arg1:string,arg2:string,arg3:string,arg4:number):Promise<services.TTSResult>;
